# Putting It all together

In [1]:
import pandas as pd
import numpy as np
import time
import random
from MyDenceNN import MyDenceNN

random.seed(5)

In [2]:
dence = MyDenceNN(display=True)

In [3]:
X = np.array([[1], [2]])
Y = np.array([[1]])
dence.add_inputs(X)
dence.add_outputs(Y)

Input:
--------- 
X = 
[[1]
 [2]]

X has 2 featurs


Output:
--------- 
Y = 
[[1]]

Y has 1 featurs




In [4]:
X1 = np.array([[2], [5]])
Y1 = np.array([[1]])
dence.add_inputs(X1)
dence.add_outputs(Y1)

Input:
--------- 
X = 
[[1 2]
 [2 5]]

X has 2 featurs


Output:
--------- 
Y = 
[[1 1]]

Y has 1 featurs




In [5]:
X2, Y2 = np.array([[3], [9]]), np.array([[0]])
dence.add_data(X2, Y2)

#################
Current Features
-----------------
-----------------

Input:
--------- 
X = 
[[1 2 3]
 [2 5 9]]

X has 2 featurs


Output:
--------- 
Y = 
[[1 1 0]]

Y has 1 featurs




In [6]:
units = {"1": 4, "2":4, "3":2}
dence.add_units(units)

#################
Units per layer
----------------
n[1] = 4
----------------
n[2] = 4
----------------
n[3] = 2
----------------
----------------


In [7]:
dence.build()

#################
Wights and Biasses

----------------
----------------
Layer 1:
----------------
W1 = 
[[ 0.84836909  0.43174673]
 [ 0.47263494  0.58818174]
 [-0.10545182 -0.4317414 ]
 [-1.01157904 -1.26472135]]
----------------
b1 = 
[[0.]
 [0.]
 [0.]
 [0.]]
----------------
----------------



----------------
----------------
Layer 2:
----------------
W2 = 
[[-1.43089907 -0.32023291  0.80062166 -2.71375513]
 [-0.41779604  0.07144838  0.50837184 -1.24717219]
 [-0.28930064 -1.08800946  1.47581195  0.05088076]
 [ 1.01072299 -1.19353921  0.54671612 -0.91176742]]
----------------
b2 = 
[[0.]
 [0.]
 [0.]
 [0.]]
----------------
----------------



----------------
----------------
Layer 3:
----------------
W3 = 
[[-0.08634209  0.10652445  0.29564356  1.07069143]
 [ 1.05795481 -0.40474653  0.07983386 -0.58363275]]
----------------
b3 = 
[[0.]
 [0.]]
----------------
----------------



----------------
----------------
Layer 4:
----------------
W4 = 
[[ 0.63035034 -1.32677197]]
----------

In [8]:
dence.forward_propagation()

###################
Forward Propagation
###################

Layer: 1 using sigmoid activation
Layer: 2 using sigmoid activation
Layer: 3 using sigmoid activation
Layer: 4 using sigmoid activation

-------------------
-------------------
Cost: J(AL, Y) = [[0.725631]]
-------------------
-------------------



In [9]:
dence.backward_propagation()

Layer: 4 using sigmoid activation
Layer: 3 using sigmoid activation
Layer: 2 using sigmoid activation
Layer: 1 using sigmoid activation


In [10]:
new_dence = MyDenceNN()

hidden_units = {
    "1": 90,
    "2": 80,
    "3": 80,
    "4": 80,
    "5": 80,
    "6": 80,
    "7": 80,
    "8": 80,
    "9": 20
}

activations = {
    "1": "tanh",
    "2": "tanh",
    "3": "tanh",
    "4": "tanh",
    "5": "tanh",
    "6": "tanh",
    "7": "tanh",
    "8": "tanh",
    "9": "sigmoid"    
}

cost_fun = "logistic_regression"
alpha = 0.001
epochs = 100

X = np.random.randn(100, 30)
Y = np.random.randint(2, size=(1, 30))

new_dence.solve(X, Y, hidden_units, activations, cost_fun, alpha, epochs)


----------------------------------------
		  Epoch 1
----------------------------------------

-------------------
-------------------
Cost: J(AL, Y) = [[0.99761943]]
-------------------
-------------------


----------------------------------------
		  Epoch 2
----------------------------------------

-------------------
-------------------
Cost: J(AL, Y) = [[1.37444573]]
-------------------
-------------------


----------------------------------------
		  Epoch 3
----------------------------------------

-------------------
-------------------
Cost: J(AL, Y) = [[1.34026489]]
-------------------
-------------------


----------------------------------------
		  Epoch 4
----------------------------------------

-------------------
-------------------
Cost: J(AL, Y) = [[1.20048133]]
-------------------
-------------------


----------------------------------------
		  Epoch 5
----------------------------------------

-------------------
-------------------
Cost: J(AL, Y) = [[0.8797870